
import os
import webbrowser
import smtplib
import subprocess
import requests
from livekit.agents import function_tool
from email.message import EmailMessage

# --- Configuration ---
# You should ideally load these from .env, but for now we'll use placeholders or environment variables
GMAIL_USER = os.getenv("GMAIL_USER", "your_email@gmail.com") 
GMAIL_APP_PASS = os.getenv("GMAIL_APP_PASS", "your_app_password")

@function_tool
def send_email_tool(to_email: str, subject: str, body: str):
    """Sends an email using Gmail SMTP. Requires GMAIL_USER and GMAIL_APP_PASS env vars."""
    try:
        if not GMAIL_USER or not GMAIL_APP_PASS:
            return "Error: Gmail credentials not configured in environment variables."
            
        msg = EmailMessage()
        msg.set_content(body)
        msg['Subject'] = subject
        msg['From'] = GMAIL_USER
        msg['To'] = to_email

        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
            smtp.login(GMAIL_USER, GMAIL_APP_PASS)
            smtp.send_message(msg)
        return f"Email sent successfully to {to_email}"
    except Exception as e:
        return f"Failed to send email: {e}"

@function_tool
def play_media_tool(query: str):
    """Plays a song or video on YouTube by searching for the query."""
    try:
        # Search on YouTube
        search_url = f"https://www.youtube.com/results?search_query={query.replace(' ', '+')}"
        # We can also try to directly open the first video if we used pywhatkit, but webbrowser is safer dependency-wise
        # For a "play" experience, we'll open the search results.
        # If the user wants to play directly, pywhatkit.playonyt(query) is better if installed.
        try:
            import pywhatkit
            pywhatkit.playonyt(query)
            return f"Playing {query} on YouTube."
        except ImportError:
            webbrowser.open(search_url)
            return f"Opened YouTube search for: {query}"
    except Exception as e:
        return f"Error playing media: {e}"

@function_tool
def shop_online_tool(item: str, website: str = "amazon"):
    """Searches for an item on Amazon or Flipkart and opens the page."""
    try:
        website = website.lower()
        if "amazon" in website:
            url = f"https://www.amazon.in/s?k={item.replace(' ', '+')}"
            webbrowser.open(url)
            return f"Searching for {item} on Amazon..."
        elif "flipkart" in website:
            url = f"https://www.flipkart.com/search?q={item.replace(' ', '+')}"
            webbrowser.open(url)
            return f"Searching for {item} on Flipkart..."
        else:
            # Fallback to general google shopping or search
            url = f"https://www.google.com/search?tbm=shop&q={item.replace(' ', '+')}"
            webbrowser.open(url)
            return f"Searching for {item} on Google Shopping..."
    except Exception as e:
        return f"Shopping tool error: {e}"

@function_tool
def download_file_tool(url: str, filename: str = None):
    """Downloads a file from a direct URL."""
    try:
        response = requests.get(url, stream=True)
        response.raise_for_status()
        
        if not filename:
            filename = url.split("/")[-1]
            if not filename:
                filename = "downloaded_file"
        
        # Save to Downloads folder or current directory
        download_path = os.path.join(os.path.expanduser("~"), "Downloads", filename)
        
        with open(download_path, 'wb') as f:
            for chunk in response.iter_content(chunk_size=8192):
                f.write(chunk)
                
        return f"File downloaded successfully to: {download_path}"
    except Exception as e:
        return f"Download failed: {e}"

@function_tool
def coding_agent_tool(project_name: str, task_description: str):
    """Creates a new project folder, an implementation plan, and opens VS Code."""
    try:
        base_path = os.path.join(os.path.expanduser("~"), "Documents", "Niranjan_Projects")
        project_path = os.path.join(base_path, project_name)
        
        if not os.path.exists(project_path):
            os.makedirs(project_path)
            
        # Create a simple README/Plan
        readme_path = os.path.join(project_path, "README.md")
        with open(readme_path, "w") as f:
            f.write(f"# {project_name}\n\n## Objective\n{task_description}\n\n## Generated by Niranjan AI")
            
        # Open in VS Code
        # Assuming 'code' is in PATH
        subprocess.Popen(["code", project_path], shell=True)
        
        return f"Created project '{project_name}' at {project_path} and opened VS Code."
    except Exception as e:
        return f"Coding agent error: {e}"

@function_tool
def send_whatsapp_tool(phone_number: str, message: str):
    """
    Sends a WhatsApp message instantly. 
    Requires pywhatkit and being logged into WhatsApp Web in the default browser.
    Phone number should include country code (e.g., '+91XXXXXXXXXX').
    """
    try:
        import pywhatkit
        # sendwhatmsg_instantly opens the browser and sends the message
        # wait_time is how long it waits for the page to load before sending (default 15s)
        pywhatkit.sendwhatmsg_instantly(
            phone_no=phone_number,
            message=message,
            wait_time=15,
            tab_close=True
        )
        return f"WhatsApp message scheduled/sent to {phone_number}."
    except Exception as e:
        return f"WhatsApp automation error: {e}"
