
import os
import webbrowser
import smtplib
import subprocess
import requests

# --- Mocking the tools logic directly for verification ---

def shop_online_tool(item: str, website: str = "amazon"):
    """Searches for an item on Amazon or Flipkart and opens the page."""
    try:
        website = website.lower()
        if "amazon" in website:
            url = f"https://www.amazon.in/s?k={item.replace(' ', '+')}"
            webbrowser.open(url)
            return f"Searching for {item} on Amazon..."
        elif "flipkart" in website:
            url = f"https://www.flipkart.com/search?q={item.replace(' ', '+')}"
            webbrowser.open(url)
            return f"Searching for {item} on Flipkart..."
        else:
            url = f"https://www.google.com/search?tbm=shop&q={item.replace(' ', '+')}"
            webbrowser.open(url)
            return f"Searching for {item} on Google Shopping..."
    except Exception as e:
        return f"Shopping tool error: {e}"

def coding_agent_tool(project_name: str, task_description: str):
    """Creates a new project folder, an implementation plan, and opens VS Code."""
    try:
        base_path = os.path.join(os.path.expanduser("~"), "Documents", "Niranjan_Projects")
        project_path = os.path.join(base_path, project_name)
        
        if not os.path.exists(project_path):
            os.makedirs(project_path)
            
        readme_path = os.path.join(project_path, "README.md")
        with open(readme_path, "w") as f:
            f.write(f"# {project_name}\n\n## Objective\n{task_description}\n\n## Generated by Niranjan AI")
            
        # Try opening with 'code'
        try:
             subprocess.Popen(["code", project_path], shell=True)
             opened = "and opened VS Code."
        except:
             opened = "(VS Code command not found, but folder created)."
        
        return f"Created project '{project_name}' at {project_path} {opened}"
    except Exception as e:
        return f"Coding agent error: {e}"

def play_media_tool(query: str):
    try:
        # Check pywhatkit manually
        try:
            import pywhatkit
            print("(PyWhatKit found, would play)")
            # pywhatkit.playonyt(query) # Commented out to avoid auto-playing sound during test if unwanted
            return f"PyWhatKit ready to play {query}"
        except ImportError:
            search_url = f"https://www.youtube.com/results?search_query={query.replace(' ', '+')}"
            webbrowser.open(search_url)
            return f"Opened YouTube search for: {query}"
    except Exception as e:
        return f"Error playing media: {e}"

if __name__ == "__main__":
    print("--- Running Logic Verification ---")
    print(shop_online_tool("Macbook Pro", "amazon"))
    print(coding_agent_tool("Niranjan_Test_App", "Verify system upgrade"))
    print(play_media_tool("Interstellar Theme"))
    print("--- Verified ---")
